name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: jsii/superchain
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          set -e
          set -x
          rm -rf package-lock.json node_modules
          npm install
          echo '{"domain": "mydomain"}' >> ./settings.json
          (cd app/npm-follower && ln -s ../lib)
          export AWS_DEFAULT_REGION="us-east-1"
          npx cdk synth
